site_name: Flaskteroids
site_url: https://nullco.github.io/flaskteroids
repo_url: https://github.com/nullco/flaskteroids
theme:
  name: material

  palette:
    - scheme: default
      primary: black
      accent: deep orange
      toggle:
        icon: material/toggle-switch 
        name: Switch to dark mode

    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  icon:
    logo: material/flask-round-bottom
    repo: fontawesome/brands/github-alt

nav:
  - Introduction: index.md
  - Getting Started:
    - Overview: getting_started.md
    - Project Structure: project_structure.md
  - Models:
    - Overview: models/index.md
  - Views:
    - Overview: views/index.md
  - Controllers:
    - Overview: controllers/index.md
    - Routing: controllers/routing.md
    - Advanced topics: controllers/advanced.md
  - Other Components:
    - CLI: other/cli.md
    - Fields: other/fields.md
    - Forms: other/forms.md
    - Background Jobs: other/jobs.md
    - Mailers: other/mailers.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
